on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Commit Push
        run: |
          git config --global user.email "17771258@qq.com"
          git config --global user.name "Yunlong"
          git checkout master
          echo ${{ github.ref }} >> version
          git add .
          git commit -m "editor version" -a
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/WuYunlong/GithubLearn/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
